import * as Utils from "./utils.ts";
import * as Quiz from "./quizEngine.ts";
import * as Questions from "./questionList.ts"

let quizSpace : HTMLDivElement;
let scoreSpace : HTMLDivElement;
let submitButton : HTMLButtonElement;;
let pool:Quiz.QuestionBank = new Quiz.QuestionBank();


function PopulateGlobalHTMLElements() {
	// Answers space
	let tmp_quizSpace = document.getElementById("quizSpace") as HTMLDivElement | null;
	if(!tmp_quizSpace) Utils.Assert(false, "Can't find quizSpace div!");
	else quizSpace = tmp_quizSpace;
	
	// Score space
	let tmp_scoreSpace = document.getElementById("scoreSpace") as HTMLDivElement | null;
	if(!tmp_scoreSpace) Utils.Assert(false, "Can't find scoreSpace div!");
	else scoreSpace = tmp_scoreSpace;
	
	// Button
	let tmp_button = document.getElementById("submitAnswers") as HTMLButtonElement | null;
	if(!tmp_button) Utils.Assert(false, "Can't find submitAnswers div!");
	else submitButton = tmp_button;


	submitButton.addEventListener("click", CheckQuestions);
}

function CreateQuestions() {
	pool.AddSA("1. What is the purpose of the OSI physical layer?", null, "transmitting bits across the local media", ["controlling access to media", "performing error detection on received frames", "exchanging frames between nodes over physical network media"], null,1);
	pool.AddSA("2. Why are two strands of fiber used for a single fiber optic connection?", null, "They allow for full-duplex connectivity.", ["The two strands allow the data to travel for longer distances without degrading.", "They prevent crosstalk from causing interference on the connection.", "They increase the speed at which the data can travel."], null,1);
	pool.AddSA("3. Which characteristic describes crosstalk?", null, "the distortion of the transmitted messages from signals carried in adjacent wires", ["the distortion of the network signal from fluorescent lighting", "the weakening of the network signal over long cable lengths", "the loss of wireless signal over excessive distance from the access point"], null,1);
	pool.AddSA("4. Which procedure is used to reduce the effect of crosstalk in copper cables?", null, "twisting opposing circuit wire pairs together", ["requiring proper grounding connections", "wrapping the bundle of wires with metallic shielding", "designing a cable infrastructure to avoid crosstalk interference", "avoiding sharp bends during installation"], null,1);
	pool.AddNA("5. Match the situation with the appropriate use of network media.", "<img src=https://itexamanswers.net/wp-content/uploads/2019/12/2020-01-11_180101-1536x862-1.jpg></img>", null);
	pool.AddMA("6. A network administrator is measuring the transfer of bits across the company backbone for a mission critical financial application. The administrator notices that the network throughput appears lower than the bandwidth expected. Which three factors could influence the differences in throughput? (Choose three.)", null, ["the amount of traffic that is currently crossing the network", "the type of traffic that is crossing the network", "the latency that is created by the number of network devices that the data is crossing"], ["the sophistication of the encapsulation method applied to the data", "the bandwidth of the WAN connection to the Internet", "the reliability of the gigabit Ethernet infrastructure of the backbone"], "Throughput usually does not match the specified bandwidth of physical links due to multiple factors. These factors include, the amount of traffic, type of traffic, and latency created by the network devices the data has to cross.",1);
	pool.AddMA("7. What are two characteristics of fiber-optic cable? (Choose two.)", null, ["It is not affected by EMI or RFI.", "It is more expensive than UTP cabling is."], ["Each pair of cables is wrapped in metallic foil.", "It combines the technique of cancellation, shielding, and twisting to protect data.", "It typically contains 4 pairs of fiber-optic wires."], "Fiber-optic cabling supports higher bandwidth than UTP for longer distances. Fiber is immune to EMI and RFI, but costs more, requires more skill to install, and requires more safety precautions.",1);
	pool.AddSA("8. What is a primary role of the Physical layer in transmitting data on the network?", null, "create the signals that represent the bits in each frame on to the media", ["provide physical addressing to the devices", "determine the path packets take through the network", "control data access to the media"], "The OSI physical layer provides the means to transport the bits that make up a frame across the network media. This layer accepts a complete frame from the data link layer and encodes it as a series of signals that are transmitted to the local media.",1);
	pool.AddSA("9. With the use of unshielded twisted-pair copper wire in a network, what causes crosstalk within the cable pairs?", null, "the magnetic field around the adjacent pairs of wire", ["the use of braided wire to shield the adjacent wire pairs", "the reflection of the electrical wave back from the far end of the cable", "the collision caused by two nodes trying to use the media simultaneously"], "Crosstalk is a type of noise, or interference that occurs when signal transmission on one wire interferes with another wire. When current flows through a wire a magnetic field is produced. The produced magnetic field will interface the signal carried in the adjacent wire.",1);
	pool.AddSA("10. Refer to the graphic. What type of cabling is shown?", "<img src=https://itexamanswers.net/wp-content/uploads/2019/12/2020-01-11_180314-300x234-1.jpg></img>", "fiber", ["STP", "UTP", "coax", "UTP cable consists of four pairs of color-coded wires that have been twisted together and then encased in a flexible plastic sheath.", "STP cable uses four pairs of wires, each wrapped in a foil shield, which are then wrapped in an overall metallic braid or foil.", "Coaxial cable uses a copper conductor and a layer of flexible plastic insulation surrounds the copper conductor.", "Fiber cable is a flexible, extremely thin, transparent strand of glass surrounded by plastic insulation."], "Network cabling include different types of cables:",1);
	pool.AddMA("11. In addition to the cable length, what two factors could interfere with the communication carried over UTP cables? (Choose two.)", null, ["crosstalk", "electromagnetic interference", "Electromagnetic interference (EMI) or radio frequency interference (RFI)** – EMI and RFI signals can distort and corrupt the data signals being carried by copper medi", "Crosstalk** – Crosstalk is a disturbance caused by the electric or magnetic fields of a signal on one wire interfering with the signal in an adjacent wir"], ["bandwidth", "size of the network", "signal modulation technique"], "Copper media is widely used in network communications. However, copper media is limited by distance and signal interference. Data is transmitted on copper cables as electrical pulses. The electrical pulses are susceptible to interference from two sources:",1);
	pool.AddSA("12. Refer to the graphic. What type of cabling is shown?", "<img src=https://itexamanswers.net/wp-content/uploads/2019/12/2020-01-11_180547.jpg></img>", "UTP", ["STP", "coax", "fiber"], null,1);
	pool.AddMA("13. Which two devices commonly affect wireless networks? (Choose two.)", null, ["cordless phones", "microwaves"], ["Blu-ray players", "home theaters", "incandescent light bulbs", "external hard drives"], "Radio Frequency Interference (RFI) is the interference that is caused by radio transmitters and other devices that are transmitting in the same frequency.",1);
	pool.AddMA("14. Which two statements describe the services provided by the data link layer? (Choose two.)", null, ["It manages the access of frames to the network media.", "It packages various Layer 3 PDUs into a frame format that is compatible with the network interface."], ["It defines the end-to-end delivery addressing scheme.", "It maintains the path between the source and destination devices during the data transmission.", "It provides reliable delivery through link establishment and flow control.", "It ensures that application data will be transmitted according to the prioritization."], "The data link layer is divided into two sub layers, namely Logical Link Control (LLC) and Media Access Control (MAC). LLC forms a frame from the network layer PDU into a format that conforms to the requirements of the network interface and media. A network layer PDU might be for IPv4 or IPv6. The MAC sub layer defines the media access processes performed by the hardware. It manages the frame access to the network media according to the physical signaling requirements (copper cable, fiber optic, wireless, etc.)",1);
	pool.AddSA("15. What is the function of the CRC value that is found in the FCS field of a frame?", null, "to verify the integrity of the received frame", ["to verify the physical address in the frame", "to verify the logical address in the frame", "to compute the checksum header for the data field in the frame"], "The CRC value in the FCS field of the received frame is compared to the computed CRC value of that frame, in order to verify the integrity of the frame. If the two values do not match, then the frame is discarded.",1);
	pool.AddSA("16. What is contained in the trailer of a data-link frame?", null, "error detection", ["logical address", "physical address", "data"], "The trailer in a data-link frame contains error detection information that is pertinent to the frame included in the FCS field. The header contains control information, such as the addressing, while the area that is indicated by the word “data” includes the data, transport layer PDU, and the IP header.",1);
	pool.AddSA("17. Which statement describes a characteristic of the frame header fields of the data link layer?", null, "They vary depending on protocols.", ["They all include the flow control and logical connection fields.", "Ethernet frame header fields contain Layer 3 source and destination addresses.", "They include information on user applications."], "All data link layer protocols encapsulate the Layer 3 PDU within the data field of the frame. However, the structure of the frame and the fields that are contained in the header vary according to the protocol. Different data link layer protocols may use different fields, like priority/quality of service, logical connection control, physical link control, flow control, and congestion control.",1);
	pool.AddSA("18. A network team is comparing physical WAN topologies for connecting remote sites to a headquarters building. Which topology provides high availability and connects some, but not all, remote sites?", null, "partial mesh", ["mesh", "hub and spoke", "point-to-point"], "Partial mesh topologies provide high availability by interconnecting multiple remote sites, but do not require a connection between all remote sites. A mesh topology requires point-to-point links with every system being connected to every other system. A point-to-point topology is where each device is connected to one other device. A hub and spoke uses a central device in a star topology that connects to other point-to-point devices.",1);
	pool.AddMA("19. Which two fields or features does Ethernet examine to determine if a received frame is passed to the data link layer or discarded by the NIC? (Choose two.)", null, ["Frame Check Sequence", "minimum frame size"], ["auto-MDIX", "CEF", "source MAC address"], "An Ethernet frame is not processed and is discarded if it is smaller than the minimum (64 bytes) or if the calculated frame check sequence (FCS) value does not match the received FCS value. Auto-MDIX (automatic medium-dependent interface crossover) is Layer 1 technology that detects cable straight-through or crossover types. The source MAC address is not used to determine how the frame is received. CEF (Cisco Express Forwarding) is a technology used to expedite Layer 3 switching.",1);
	pool.AddSA("20. Which media communication type does not require media arbitration in the data link layer?", null, "full-duplex", ["deterministic", "half-duplex", "controlled access"], "Half-duplex communication occurs when both devices can both transmit and receive on the medium but cannot do so simultaneously. Full-duplex communication occurs when both devices can transmit and receive on the medium at the same time and therefore does not require media arbitration. Half-duplex communication is typically contention-based, whereas controlled (deterministic) access is applied in technologies where devices take turns to access the medium.",1);
	pool.AddSA("21. Which statement describes an extended star topology?", null, "End devices connect to a central intermediate device, which in turn connects to other central intermediate devices.", ["End devices are connected together by a bus and each bus connects to a central intermediate device.", "Each end system is connected to its respective neighbor via an intermediate device.", "All end and intermediate devices are connected in a chain to each other."], "In an extended star topology, central intermediate devices interconnect other star topologies.",1);
	pool.AddSA("22. What is a characteristic of the LLC sublayer?", null, "It places information in the frame allowing multiple Layer 3 protocols to use the same network interface and media.", ["It provides the logical addressing required that identifies the device.", "It provides delimitation of data according to the physical signaling requirements of the medium.", "It defines software processes that provide services to the physical layer."], "The Logical Link Control (LLC) defines the software processes that provide services to the network layer protocols. The information is placed by LLC in the frame and identifies which network layer protocol is being used for the frame. This information allows multiple Layer 3 protocols, such as IPv4 and IPv6, to utilize the same network interface and media.",1);
	pool.AddMA("23. What are three ways that media access control is used in networking? (Choose three.)", null, ["Ethernet utilizes CSMA/CD.", "Media access control provides placement of data frames onto the media.", "Data link layer protocols define the rules for access to different media."], ["Contention-based access is also known as deterministic.", "802.11 utilizes CSMA/CD.", "Networks with controlled access have reduced performance due to data collisions."], "Wired Ethernet networks use CSMA/CD for media access control. IEEE 802.11 wireless networks use CSMA/CA, a similar method. Media access control defines the way data frames get placed on the media. The controlled access method is deterministic, not a contention-based access to networks. Because each device has its own time to use the medium, controlled access networks such as legacy Token Ring do not have collisions.",1);
	pool.AddSA("24. During the encapsulation process, what occurs at the data link layer for a PC connected to an Ethernet network?", null, "The physical address is added.", ["An IP address is added.", "The logical address is added.", "The process port number is added."], "The Ethernet frame includes the source and destination physical address. The trailer includes a CRC value in the Frame Check Sequence field to allow the receiving device to determine if the frame has been changed (has errors) during the transmission.",1);
	pool.AddMA("25. What three items are contained in an Ethernet header and trailer? (Choose three.)", null, ["source MAC address", "destination MAC address", "error-checking information"], ["source IP address", "destination IP address", "Frame start and stop indicator flags at the beginning and end of a frame", "Addressing – for Ethernet networks this part of the header contains source and destination MAC addresses", "Type field to indicate what Layer 3 protocol is being used", "Error detection to determine if the frame arrived without error"], "Layer 2 headers contain the following:",1);
	pool.AddSA("26. What type of communication rule would best describe CSMA/CD?", null, "access method", ["flow control", "message encapsulation", "message encoding"], "Carrier sense multiple access collision detection (CSMA/CD) is the access method used with Ethernet. The access method rule of communication dictates how a network device is able to place a signal on the carrier. CSMA/CD dictates those rules on an Ethernet network and CSMA/CA dictates those rules on an 802.11 wireless LAN.",1);
	pool.AddMA("27. Which three basic parts are common to all frame types supported by the data link layer? (Choose three.)", null, ["header", "data", "trailer"], ["type field", "MTU size", "CRC value", "Header", "Data", "Trailer"], "The data link protocol is responsible for NIC-to-NIC communications within the same network. Although there are many different data link layer protocols that describe data link layer frames, each frame type has three basic parts:",1);
	pool.AddSA("28. Which statement is true about the CSMA/CD access method that is used in Ethernet?", null, "All network devices must listen before transmitting.", ["When a device hears a carrier signal and transmits, a collision cannot occur.", "A jamming signal causes only devices that caused the collision to execute a backoff algorithm.", "Devices involved in a collision get priority to transmit after the backoff period."], "Legacy bus-topology Ethernet LAN uses CSMA/CD as network media access control protocol. It works by detecting a collision in the medium and backing off (after transmitting a jam signal) as necessary. When one host wants to transmit a frame, it listens on the medium to check if the medium is busy. After it senses that no one else is transmitting, the host starts transmitting the frame, it also monitors the current level to detect a collision. If it detects a collision, it transmits a special jam signal so that all other hosts can know there was a collision. The other host will receive this jam signal and stop transmitting. After this, both hosts enter an exponential backoff phase and retry transmission.",1);
	pool.AddSA("29. What is the auto-MDIX feature on a switch?", null, "the automatic configuration of an interface for a straight-through or a crossover Ethernet cable connection", ["the automatic configuration of an interface for 10/100/1000 Mb/s operation", "the automatic configuration of full-duplex operation over a single Ethernet copper or optical cable", "the ability to turn a switch interface on or off accordingly if an active connection is detected"], "The auto-MDIX enables a switch to use a crossover or a straight-through Ethernet cable to connect to a device regardless of the device on the other end of the connection.",1);
	pool.AddSA("30. Refer to the exhibit. What is the destination MAC address of the Ethernet frame as it leaves the web server if the final destination is PC1?", "<img src=https://itexamanswers.net/wp-content/uploads/2019/12/i209881v1n2_209881.png></img>", "00-60-2F-3A-07-CC", ["00-60-2F-3A-07-AA", "00-60-2F-3A-07-BB", "00-60-2F-3A-07-DD"], "The destination MAC address is used for local delivery of Ethernet frames. The MAC (Layer 2) address changes at each network segment along the path. As the frame leaves the web server, it will be delivered by using the MAC address of the default gateway.",1);
	pool.AddSA("31. A Layer 2 switch is used to switch incoming frames from a 1000BASE-T port to a port connected to a 100Base-T network. Which method of memory buffering would work best for this task?", null, "shared memory buffering", ["port-based buffering", "level 1 cache buffering", "fixed configuration buffering"], "With shared memory buffering, the number of frames stored in the buffer is restricted only by the of the entire memory buffer and not limited to a single port buffer. This permits larger frames to be transmitted with fewer dropped frames. This is important to asymmetric switching, which applies to this scenario, where frames are being exchanged between ports of different rates. With port-based memory buffering, frames are stored in queues that are linked to specific incoming and outgoing ports making it possible for a single frame to delay the transmission of all the frames in memory because of a busy destination port. Level 1 cache is memory used in a CPU. Fixed configuration refers to the port arrangement in switch hardware.",1);
	pool.AddMA("32. What are two examples of the cut-through switching method? (Choose two.)", null, ["fast-forward switching", "fragment-free switching"], ["store-and-forward switching", "CRC switching", "QOS switching"], "Store-and forward switching accepts the entire frame and performs error checking using CRC before forwarding the frame. Store-and-forward is often required for QOS analysis. Fast-forward and fragment-free are both variations of the cut-through switching method where only part of the frame is received before the switch begins to forward it.",1);
	pool.AddSA("33. Which frame forwarding method receives the entire frame and performs a CRC check to detect errors before forwarding the frame?", null, "store-and-forward switching", ["cut-through switching", "fragment-free switching", "fast-forward switching"], "Fast-forward and fragment-free switching are variations of cut-through switching, which begins to forward the frame before the entire frame is received.",1);
	pool.AddSA("34. What is the purpose of the FCS field in a frame?", null, "to determine if errors occurred in the transmission and reception", ["to obtain the MAC address of the sending node", "to verify the logical address of the sending node", "to compute the CRC header for the data field"], "The FCS field in a frame is used to detect any errors in the transmission and receipt of a frame. This is done by comparing the CRC value within the frame against a computed CRC value of the frame. If the two values do not match, then the frame is discarded.",1);
	pool.AddSA("35. Which switching method has the lowest level of latency?", null, "fast-forward", ["cut-through", "store-and-forward", "fragment-free"], "Fast-forward switching begins to forward a frame after reading the destination MAC address, resulting in the lowest latency. Fragment-free reads the first 64 bytes before forwarding. Store-and-forward has the highest latency because it reads the entire frame before beginning to forward it. Both fragment-free and fast-forward are types of cut-through switching.",1);
	pool.AddMA("36. A network administrator is connecting two modern switches using a straight-through cable. The switches are new and have never been configured. Which three statements are correct about the final result of the connection? (Choose three.)", null, ["The link between the switches will work at the fastest speed that is supported by both switches.", "The link between switches will work as full-duplex.", "The auto-MDIX feature will configure the interfaces eliminating the need for a crossover cable."], ["If both switches support different speeds, they will each work at their own fastest speed.", "The connection will not be possible unless the administrator changes the cable to a crossover cable.", "The duplex capability has to be manually configured because it cannot be negotiated."], "Modern switches can negotiate to work in full-duplex mode if both switches are capable. They will negotiate to work using the fastest possible speed and the auto-MDIX feature is enabled by default, so a cable change is not needed.",1);
	pool.AddSA("37. Which advantage does the store-and-forward switching method have compared with the cut-through switching method?", null, "frame error checking", ["collision detecting", "faster frame forwarding", "frame forwarding using IPv4 Layer 3 and 4 information"], "A switch using the store-and-forward switching method performs an error check on an incoming frame by comparing the FCS value against its own FCS calculations after the entire frame is received. In comparison, a switch using the cut-through switching method makes quick forwarding decisions and starts the forwarding process without waiting for the entire frame to be received. Thus a switch using cut-through switching may send invalid frames to the network. The performance of store-and-forward switching is slower compared to cut-through switching performance. Collision detection is monitored by the sending device. Store-and-forward switching does not use IPv4 Layer 3 and 4 information for its forwarding decisions.",1);
	pool.AddSA("38. When the store-and-forward method of switching is in use, what part of the Ethernet frame is used to perform an error check?", null, "CRC in the trailer", ["source MAC address in the header", "destination MAC address in the header", "protocol type in the header"], "The cyclic redundancy check (CRC) part of the trailer is used to determine if the frame has been modified during transit.​ If the integrity of the frame is verified, the frame is forwarded. If the integrity of the frame cannot be verified, then the frame is dropped.",1);
	pool.AddSA("39. Which switching method uses the CRC value in a frame?", null, "store-and-forward", ["cut-through", "fast-forward", "fragment-free"], "When the store-and-forward switching method is used, the switch receives the complete frame before forwarding it on to the destination. The cyclic redundancy check (CRC) part of the trailer is used to determine if the frame has been modified during transit.​​ In contrast, a cut-through switch forwards the frame once the destination Layer 2 address is read. Two types of cut-through switching methods are fast-forward and fragment-free.",1);
	pool.AddMA("40. What are two actions performed by a Cisco switch? (Choose two.)", null, ["using the source MAC addresses of frames to build and maintain a MAC address table", "utilizing the MAC address table to forward frames via the destination MAC address"], ["building a routing table that is based on the first IP address in the frame header", "forwarding frames with unknown destination IP addresses to the default gateway", "examining the destination MAC address to add new entries to the MAC address table", "When a frame comes in, the switch examines the Layer 2 source address to build and maintain the Layer 2 MAC address table.", "It examines the Layer 2 destination address to determine how to forward the frame. When the destination address is in the MAC address table, then the frame is sent out a particular port. When the address is unknown, the frame is sent to all ports that have devices connected to that network."], "Important actions that a switch performs are as follows:",1);
	pool.AddMA("41. Which two statements describe features or functions of the logical link control sublayer in Ethernet standards? (Choose two.)", null, ["Logical link control is implemented in software.", "The data link layer uses LLC to communicate with the upper layers of the protocol suite."], ["Logical link control is specified in the IEEE 802.3 standard.", "The LLC sublayer adds a header and a trailer to the data.", "The LLC sublayer is responsible for the placement and retrieval of frames on and off the media."], "Logical link control is implemented in software and enables the data link layer to communicate with the upper layers of the protocol suite. Logical link control is specified in the IEEE 802.2 standard. IEEE 802.3 is a suite of standards that define the different Ethernet types. The MAC (Media Access Control) sublayer is responsible for the placement and retrieval of frames on and off the media. The MAC sublayer is also responsible for adding a header and a trailer to the network layer protocol data unit (PDU).",1);
	pool.AddSA("42. What is the auto-MDIX feature?", null, "It enables a device to automatically configure an interface to use a straight-through or a crossover cable.", ["It enables a device to automatically configure the duplex settings of a segment.", "It enables a device to automatically configure the speed of its interface.", "It enables a switch to dynamically select the forwarding method."], "The auto-MDIX feature allows the device to configure its network port according to the cable type that is used (straight-through or crossover) and the type of device that is connected to that port. When a port of a switch is configured with auto-MDIX, this switch can be connected to another switch by the use of either a straight-through cable or a crossover cable.",1);
	pool.AddSA("43. What is one advantage of using the cut-through switching method instead of the store-and-forward switching method?", null, "has a lower latency appropriate for high-performance computing applications​", ["has a positive impact on bandwidth by dropping most of the invalid frames", "makes a fast forwarding decision based on the source MAC address of the frame", "provides the flexibility to support any mix of Ethernet speeds"], "Cut-through switching provides lower latency switching for high-performance computing (HPC) applications. Cut-through switching allows more invalid frames to cross the network than store-and-forward switching. The cut-through switching method can make a forwarding decision as soon as it looks up the destination MAC address of the frame.",1);
	pool.AddSA("44. Which is a multicast MAC address?", null, "01-00-5E-00-00-03", ["FF-FF-FF-FF-FF-FF", "5C-26-0A-4B-19-3E", "00-26-0F-4B-00-3E"], "Multicast MAC addresses begin with the special value of 01-00-5E.",1);
	pool.AddSA("45. Refer to the exhibit. What is wrong with the displayed termination?", "<img src=https://itexamanswers.net/wp-content/uploads/2019/12/i274300v1n1_209630-300x221-1.png></img>", "The untwisted length of each wire is too long.", ["The woven copper braid should not have been removed.", "The wrong type of connector is being used.", "The wires are too thick for the connector that is used."], "When a cable to an RJ-45 connector is terminated, it is important to ensure that the untwisted wires are not too long and that the flexible plastic sheath surrounding the wires is crimped down and not the bare wires. None of the colored wires should be visible from the bottom of the jack.",1);
	pool.AddNA("46. Refer to the exhibit. The PC is connected to the console port of the switch. All the other connections are made through FastEthernet links. Which types of UTP cables can be used to connect the devices?​", "<img src=https://itexamanswers.net/wp-content/uploads/2019/12/i274301v1n1_206934.png></img>", "A straight-through cable is commonly used to interconnect a host to a switch and a switch to a router. A crossover cable is used to interconnect similar devices together like switch to a switch, a host to a host, or a router to a router. If a switch has the MDIX capability, a crossover could be used to connect the switch to the router; however, that option is not available. A rollover cable is used to connect to a router or switch console port.");
	pool.AddSA("47. Open the PT Activity. Perform the tasks in the activity instructions and then answer the question.", null, "Fa0/11", ["Fa0/1", "Fa0/5", "Fa0/9"], "Issuing the command **ipconfig /all** from the PC0 command prompt displays the IPv4 address and MAC address. When the IPv4 address 10.1.1.5 is pinged from PC0, the switch stores the source MAC address (from PC0) along with the port to which PC0 is connected. When the destination reply is received, the switch takes the destination MAC address and compares to MAC addresses stored in the MAC address table. Issuing the **show mac-address-table** on the PC0 Terminal application displays two dynamic MAC address entries. The MAC address and port entry that does not belong to PC0 must be the MAC address and port of the destination with the IPv4 address 10.1.1.5.",1);
	pool.AddSA("48. What does the term “attenuation” mean in data communication?", null, "loss of signal strength as distance increases", ["time for a signal to reach its destination", "leakage of signals from one cable pair to another", "strengthening of a signal by a networking device"], "Data is transmitted on copper cables as electrical pulses. A detector in the network interface of a destination device must receive a signal that can be successfully decoded to match the signal sent. However, the farther the signal travels, the more it deteriorates. This is referred to as signal attenuation.",1);
	pool.AddMA("49. What makes fiber preferable to copper cabling for interconnecting buildings? (Choose three.)", null, ["greater distances per cable run", "limited susceptibility to EMI/RFI", "greater bandwidth potential"], ["lower installation cost", "durable connections", "easily terminated"], "Optical fiber cable transmits data over longer distances and at higher bandwidths than any other networking media. Unlike copper wires, fiber-optic cable can transmit signals with less attenuation and is completely immune to EMI and RFI.",1);
	pool.AddSA("50. What OSI physical layer term describes the process by which one wave modifies another wave?", null, "modulation", ["IEEE", "EIA/TIA", "air"], null,1);
	pool.AddSA("51. What OSI physical layer term describes the capacity at which a medium can carry data?", null, "bandwidth", ["IEEE", "EIA/TIA", "air"], null,1);
	pool.AddSA("53. What OSI physical layer term describes the measure of the transfer of bits across a medium over a given period of time?", null, "throughput", ["bandwidth", "latency", "goodput"], null,1);
	pool.AddSA("54. What OSI physical layer term describes the amount of time, including delays, for data to travel from one point to another?", null, "latency", ["bandwidth", "throughput", "goodput"], null,1);
	pool.AddSA("55. What OSI physical layer term describes the amount of time, including delays, for data to travel from one point to another?", null, "latency", ["fiber-optic cable", "air", "copper cable"], null,1);
	pool.AddSA("56. What OSI physical layer term describes the measure of usable data transferred over a given period of time?", null, "goodput", ["fiber-optic cable", "air", "copper cable"], null,1);
	pool.AddSA("57. What OSI physical layer term describes the physical medium which uses electrical pulses?", null, "copper cable", ["fiber-optic cable", "air", "goodput"], null,1);
	pool.AddSA("58. What OSI physical layer term describes the physical medium that uses the propagation of light?", null, "fiber-optic cable", ["goodput", "latency", "throughput"], null,1);
	pool.AddSA("59. What OSI physical layer term describes the physical medium for microwave transmissions?", null, "air", ["goodput", "latency", "throughput"], null,1);
	pool.AddMA("60.1 Which two functions are performed at the MAC sublayer of the OSI data link layer? (Choose two.)", null, ["Controls the NIC responsible for sending and receiving data on the physical medium.", "Implements a trailer to detect transmission errors."], ["Adds Layer 2 control information to network protocol data.", "Places information in the frame that identifies which network layer protocol is being used for the frame.", "Enables IPv4 and IPv6 to utilize the same network interface and media."], null,1);
	pool.AddMA("60.2 Which two functions are performed at the MAC sublayer of the OSI data link layer? (Choose two.)", null, ["Provides synchronization between source and target nodes.", "Integrates various physical technologies."], ["Communicates between the networking software at the upper layers and the device hardware at the lower layers.", "Adds Layer 2 control information to network protocol data.", "Enables IPv4 and IPv6 to utilize the same network interface and media."], null,1);
	pool.AddMA("60.3 Which two functions are performed at the MAC sublayer of the OSI data link layer? (Choose two.)", null, ["Provides synchronization between source and target nodes.", "Implements a trailer to detect transmission errors."], ["Enables IPv4 and IPv6 to utilize the same network interface and media.", "Adds Layer 2 control information to network protocol data.", "Places information in the frame that identifies which network layer protocol is being used for the frame."], null,1);
	pool.AddMA("60.4 Which two functions are performed at the MAC sublayer of the OSI data link layer? (Choose two.)", null, ["Integrates various physical technologies.", "Provides synchronization between source and target nodes."], ["Enables IPv4 and IPv6 to utilize the same network interface and media.", "Adds Layer 2 control information to network protocol data.", "Communicates between the networking software at the upper layers and the device hardware at the lower layers."], null,1);
	pool.AddMA("60.5 Which two functions are performed at the MAC sublayer of the OSI data link layer? (Choose two.)", null, ["Integrates various physical technologies.", "Controls the NIC responsible for sending and receiving data on the physical medium."], ["Places information in the frame that identifies which network layer protocol is being used for the frame.", "Adds Layer 2 control information to network protocol data.", "Communicates between the networking software at the upper layers and the device hardware at the lower layers."], null,1);
	pool.AddMA("60.6 Which two functions are performed at the MAC sublayer of the OSI data link layer? (Choose two.)", null, ["Controls the NIC responsible for sending and receiving data on the physical medium", "Provides a mechanism to allow multiple devices to communicate over a shared medium."], [], null,1);
	pool.AddMA("61. Which two functions are performed at the LLC sublayer of the OSI data link layer? (Choose two.)", null, ["Enables IPv4 and IPv6 to utilize the same network interface and media.", "Places information in the frame that identifies which network layer protocol is being used for the frame."], ["Integrates various physical technologies.", "Implements a process to delimit fields within a Layer 2 frame.", "Controls the NIC responsible for sending and receiving data on the physical medium."], null,1);
	pool.AddMA("64. Which two functions are performed at the LLC sublayer of the OSI data link layer? (Choose two.)", null, ["Adds Layer 2 control information to network protocol data.", "Places information in the frame that identifies which network layer protocol is being used for the frame."], ["Performs data encapsulation.", "Controls the NIC responsible for sending and receiving data on the physical medium.", "Integrates various physical technologies."], null,1);
	pool.AddMA("66. Which two functions are performed at the LLC sublayer of the OSI data link layer? (Choose two.)", null, ["Adds Layer 2 control information to network protocol data.", "Enables IPv4 and IPv6 to utilize the same network interface and media."], ["Provides data link layer addressing.", "Implements a trailer to detect transmission errors.", "Provides synchronization between source and target nodes."], null,1);
	pool.AddMA("68. Which two functions are performed at the LLC sublayer of the OSI data link layer? (Choose two.)", null, ["Enables IPv4 and IPv6 to utilize the same network interface and media.", "Adds Layer 2 control information to network protocol data."], ["Integrates various physical technologies.", "Implements a trailer to detect transmission errors.", "Provides synchronization between source and target nodes."], null,1);
	pool.AddSA("71. What action will occur if a switch receives a frame with the destination MAC address FF:FF:FF:FF:FF:FF?", null, "The switch forwards it out all ports except the ingress port.", ["The switch shares the MAC address table entry with any connected switches.", "The switch does not forward the frame.", "The switch sends the frame to a connected router because the destination MAC address is not local."], null,1);
	pool.AddSA("73. What action will occur if a switch receives a frame with the destination MAC address 01:00:5E:00:00:D9?", null, "The switch forwards it out all ports except the ingress port.", ["The switch does not forward the frame.", "The switch sends the frame to a connected router because the destination MAC address is not local.", "The switch shares the MAC address table entry with any connected switches."], null,1);
	pool.AddSA("74. What action will occur if a host receives a frame with a destination MAC address of FF:FF:FF:FF:FF:FF?", null, "The host will process the frame.", ["The host forwards the frame to the router.", "The host sends the frame to the switch to update the MAC address table.", "The host forwards the frame to all other hosts."], null,1);
	pool.AddSA("75. What action will occur if a switch receives a frame and does have the source MAC address in the MAC table?", null, "The switch refreshes the timer on that entry.", ["The switch adds it to its MAC address table associated with the port number.", "The switch forwards the frame to the associated port.", "The switch sends the frame to a connected router because the destination MAC address is not local."], null,1);
	pool.AddSA("76. What action will occur if a host receives a frame with a destination MAC address of FF:FF:FF:FF:FF:FF?", null, "The host will process the frame.", ["The host returns the frame to the switch.", "The host replies to the switch with its own IP address.", "The host forwards the frame to all other hosts."], null,1);
	pool.AddSA("78. What action will occur if a host receives a frame with a destination MAC address it does not recognize?", null, "The host will discard the frame.", ["The host replies to the switch with its own IP address.", "The host forwards the frame to all other hosts.", "The host returns the frame to the switch."], null,1);
	//Done!
	



	// pool.AddSA('1. During a routine inspection, a technician discovered that software that was installed on a computer was secretly collecting data about websites that were visited by users of the computer. Which type of threat is affecting this computer?', null, 'spyware', ['DoS attack​','identity theft','zero-day attack'], 1, null);
	// pool.AddSA('2. Which term refers to a network that provides secure access to the corporate offices by suppliers, customers and collaborators?', null, 'extranet', ['Internet','intranet','extendednet'], 1, null);
	// pool.AddSA('3. A large corporation has modified its network to allow users to access network resources from their personal laptops and smart phones. Which networking trend does this describe?', null, 'bring your own device', ['cloud computing','online collaboration','video conferencing'], 1, null);
	// pool.AddSA('4. What is an ISP?', null, 'It is an organization that enables individuals and businesses to connect to the Internet.', ['It is a standards body that develops cabling and wiring standards for networking.','It is a protocol that establishes how computers within a local network communicate.','It is a networking device that combines the functionality of several different networking devices in one.'], 1, null);
	// pool.AddNA('5. Match the requirements of a reliable network with the supporting network architecture. (Not all options are used.)', null, null);
	// pool.AddSA('6. An employee at a branch office is creating a quote for a customer. In order to do this, the employee needs to access confidential pricing information from internal servers at the Head Office. What type of network would the employee access?', null, 'an intranet', ['the Internet','an extranet','a local area network'], 1, null);
	// pool.AddSA('8. A networking technician is working on the wireless network at a medical clinic. The technician accidentally sets up the wireless network so that patients can see the medical records data of other patients. Which of the four network characteristics has been violated in this situation?', null, 'security', ['fault tolerance','scalability','Quality of Service (QoS)','reliability'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Network security includes protecting the confidentiality of data that is on the network. In this case, because confidential data has been made available to unauthorized users, the security characteristic of the network has failed.</p></div>');
	// pool.AddNA('9. Match each characteristic to its corresponding Internet connectivity type. (Not all options are used.)', '<img src="https://a5m9a8c3.rocketcdn.me/wp-content/uploads/2019/12/2021-09-13_105339.jpg">', '<div class="message_box success"><p><strong>Explanation:</strong> DSL is an always-on, high bandwidth connection that runs over telephone lines. Cable uses the same coaxial cable that carries television signals into the home to provide Internet access. Dialup telephone is much slower than either DSL or cable, but is the least expensive option for home users because it can use any telephone line and a simple modem. Satellite requires a clear line of sight and is affected by trees and other obstructions. None of these typical home options use dedicated leased lines such as T1/E1 and T3/E3.</p></div>');
	// pool.AddMA('10. What two criteria are used to help select a network medium from various network media? (Choose two.)', null, ['the distance the selected medium can successfully carry a signal','the environment where the selected medium is to be installed'], ['the types of data that need to be prioritized','the cost of the end devices utilized in the network','the number of intermediate devices installed in the network'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Criteria for choosing a network medium are the distance the selected medium can successfully carry a signal, the environment in which the selected medium is to be installed, the amount of data and the speed at which the data must be transmitted, and the cost of the medium and its installation.</p></div>');
	// pool.AddSA('11. What type of network traffic requires QoS?', null, 'video conferencing', ['email','on-line purchasing','wiki'], 1, null);
	// pool.AddMA('12. A user is implementing security on a small office network. Which two actions would provide the minimum security requirements for this network? (Choose two.)', null, ['implementing a firewall','installing antivirus software'], ['installing a wireless network','implementing an intrusion detection system','adding a dedicated intrusion prevention device'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Technically complex security measures such as intrusion prevention and intrusion prevention systems are usually associated with business networks rather than home networks. Installing antivirus software, antimalware software, and implementing a firewall will usually be the minimum requirements for home networks. Installing a home wireless network will not improve network security, and will require further security actions to be taken.</p></div>');
	// pool.AddMA('13. Passwords can be used to restrict access to all or parts of the Cisco IOS. Select the modes and interfaces that can be protected with passwords. (Choose three.)', null, ['VTY interface','console interface','privileged EXEC mode'], ['Ethernet interface','boot IOS mode','router configuration mode'], 1, null);
	// pool.AddSA('15. What function does pressing the Tab key have when entering a command in IOS?', null, 'It completes the remainder of a partially typed word in a command.', ['It aborts the current command and returns to configuration mode.','It exits configuration mode and returns to user EXEC mode.','It moves the cursor to the beginning of the next line.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Pressing the Tab key after a command has been partially typed will cause the IOS to complete the rest of the command.</p></div>');
	// pool.AddSA('16. While trying to solve a network issue, a technician made multiple changes to the current router configuration file. The changes did not solve the problem and were not saved. What action can the technician take to discard the changes and work with the file in NVRAM?', null, 'Issue the reload command without saving the running configuration.', ['Delete the vlan.dat file and reboot the device.','Close and reopen the terminal emulation software.','Issue the copy startup-config running-config command.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> The technician does not want to make any mistakes trying to remove all the changes that were done to the running configuration file. The solution is to reboot the router without saving the running configuration. The copy startup-config running-config command does not overwrite the running configuration file with the configuration file stored in NVRAM, but rather it just has an additive effect.</p></div>');
	// pool.AddSA('17. An administrator uses the Ctrl-Shift-6 key combination on a switch after issuing the ping command. What is the purpose of using these keystrokes?', null, 'to interrupt the ping process', ['to restart the ping process','to exit to a different configuration mode','to allow the user to complete the command'], 1, null);

	// pool.AddNA('19. A technician configures a switch with these commands:', null, null);
	// pool.AddSA('20. Which command or key combination allows a user to return to the previous level in the command hierarchy?', null, 'exit', ['end','Ctrl-Z','Ctrl-C'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> End and CTRL-Z return the user to the privileged EXEC mode. Ctrl-C ends a command in process. The exit command returns the user to the previous level.</p></div>');

	// pool.AddSA('23. How is SSH different from Telnet?', null, 'SSH provides security to remote sessions by encrypting messages and using user authentication. Telnet is considered insecure and sends messages in plaintext.', ['SSH makes connections over the network, whereas Telnet is for out-of-band access.','SSH requires the use of the PuTTY terminal emulation program. Tera Term must be used to connect to devices through the use of Telnet.','SSH must be configured over an active network connection, whereas Telnet is used to connect to a device from a console connection.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> SSH is the preferred protocol for connecting to a device operating system over the network because it is much more secure than Telnet. Both SSH and Telnet are used to connect to devices over the network, and so are both used in-band. PuTTY and Terra Term can be used to make both SSH and Telnet connections.</p></div>');
	// pool.AddNA('24. An administrator is configuring a switch console port with a password. In what order will the administrator travel through the IOS modes of operation in order to reach the mode in which the configuration commands will be entered? (Not all options are used.)', '<img src="https://a5m9a8c3.rocketcdn.me/wp-content/uploads/2019/12/CCNA-1-v7-Modules-1-3-Basic-Network-Connectivity-and-Communications-Exam-Answers-20.jpg">', '<div class="message_box success"><p><strong>Explanation:</strong> The configuration mode that the administrator first encounters is user EXEC mode. After the <b>enable </b>command is entered, the next mode is privileged EXEC mode. From there, the<b> configure termina</b>l command is entered to move to global configuration mode. Finally, the administrator enters the<b> line console 0 </b>command to enter the mode in which the configuration will be entered.</p></div>');
	// pool.AddMA('25. What are three characteristics of an SVI? (Choose three.)', null, ['It is not associated with any physical interface on a switch.','It provides a means to remotely manage a switch.','It is associated with VLAN1 by default.'], ['It is designed as a security protocol to protect switch ports.','It is a special interface that allows connectivity by different types of media.','It is required to allow connectivity by any device at any location.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Switches have one or more switch virtual interfaces (SVIs). SVIs are created in software since there is no physical hardware associated with them. Virtual interfaces provide a means to remotely manage a switch over a network that is using IP. Each switch comes with one SVI appearing in the default configuration “out-of-the-box.” The default SVI interface is VLAN1.</p></div>');
	// pool.AddSA('26. What command is used to verify the condition of the switch interfaces, including the status of the interfaces and a configured IP address?', null, 'show ip interface brief', ['ipconfig','ping','traceroute'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> The show ip interface brief command is used to display a brief synopsis of the condition of the device interfaces. The ipconfig command is used to verify TCP/IP properties on a host. The ping command is used to verify Layer 3 connectivity. The traceroute command is used to trace the network path from source to destination.</p></div>');
	// pool.AddNA('27. Match the description with the associated IOS mode. (Not all options are used.)', null, null);
	// pool.AddNA('28. Match the definitions to their respective CLI hot keys and shortcuts. (Not all options are used.) Explanation: The shortcuts with their functions are as follows: – Tab – Completes the remainder of a partially typed command or keyword – Space bar – displays the next screen – ? – provides context-sensitive help – Up Arrow – Allows user to scroll backward through former commands – Ctrl-C – cancels any command currently being entered and returns directly to privileged EXEC mode – Ctrl-Shift-6 – Allows the user to interrupt an IOS process such as ping or traceroute', null, null);
	// pool.AddSA('29. In the show running-config command, which part of the syntax is represented by running-config ?', null, 'a keyword', ['the command','a variable','a prompt'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> The first part of the syntax, show, is the command, and the second part of the syntax, running-config, is the keyword. The keyword specifies what should be displayed as the output of the show command.</p></div>');
	// pool.AddSA('30. After making configuration changes on a Cisco switch, a network administrator issues a copy running-config startup-config command. What is the result of issuing this command?', null, 'The new configuration will be loaded if the switch is restarted.', ['The new configuration will be stored in flash memory.','The current IOS file will be replaced with the newly configured file.','The configuration changes will be removed and the original configuration will be restored.'], 1, '<div class="message_box success"><p><b>Explanation:</b> With the <code>copy running-config startup-config</code> command, the content of the current operating configuration replaces the startup configuration file stored in NVRAM. The configuration file saved in NVRAM will be loaded when the device is restarted.</p></div>');
	// pool.AddSA('31. What command will prevent all unencrypted passwords from displaying in plain text in a configuration file?', null, '(config)# service password-encryption', ['(config)# enable password secret','(config)# enable secret Secret_Password','(config-line)# password secret','(config)# enable secret Encrypted_Password'], 1, null);
	// pool.AddSA('33. What method can be used by two computers to ensure that packets are not dropped because too much data is being sent too quickly?', null, 'flow control', ['encapsulation','access method','response timeout'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> In order for two computers to be able to communicate effectively, there must be a mechanism that allows both the source and destination to set the timing of the transmission and receipt of data. Flow control allows for this by ensuring that data is not sent too fast for it to be received properly.</p></div>');
	// pool.AddSA('34. Which statement accurately describes a TCP/IP encapsulation process when a PC is sending data to the network?', null, 'Segments are sent from the transport layer to the internet layer.', ['Data is sent from the internet layer to the network access layer.','Packets are sent from the network access layer to the transport layer.','Frames are sent from the network access layer to the internet layer.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> When the data is traveling from the PC to the network, the transport layer sends segments to the internet layer. The internet layer sends packets to the network access layer, which creates frames and then converts the frames to bits. The bits are released to the network media.</p></div>');
	// pool.AddMA('35. What three application layer protocols are part of the TCP/IP protocol suite? (Choose three.)', null, ['DHCP','DNS','FTP'], ['ARP','NAT','PPP'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> DNS, DHCP, and FTP are all application layer protocols in the TCP/IP protocol suite. ARP and PPP are network access layer protocols, and NAT is an internet layer protocol in the TCP/IP protocol suite.</p></div>');
	// pool.AddNA('36. Match the description to the organization. (Not all options are used.) Explanation: The EIA is an international standards and trade organization for electronics organizations. It is best known for its standards related to electrical wiring, connectors, and the 19-inch racks used to mount networking equipment.', null, null);
	// pool.AddSA('39. What process involves placing one PDU inside of another PDU?', null, 'encapsulation', ['encoding','segmentation','flow control'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> When a message is placed inside of another message, this is known as encapsulation. On networks, encapsulation takes place when one protocol data unit is carried inside of the data field of the next lower protocol data unit.</p></div>');
	// pool.AddSA('40. What layer is responsible for routing messages through an internetwork in the TCP/IP model?', null, 'internet', ['transport','network access','session'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> The TCP/IP model consists of four layers: application, transport, internet, and network access. Of these four layers, it is the internet layer that is responsible for routing messages. The session layer is not part of the TCP/IP model but is rather part of the OSI model.</p></div>');
	// pool.AddNA('41. For the TCP/IP protocol suite, what is the correct order of events when a Telnet message is being prepared to be sent over the network?', '<img src="https://a5m9a8c3.rocketcdn.me/wp-content/uploads/2019/12/CCNA-1-v7-Modules-1-3-Basic-Network-Connectivity-and-Communications-Exam-Answers-37.jpg">', null);
	// pool.AddSA('42. Which PDU format is used when bits are received from the network medium by the NIC of a host?', null, 'frame', ['file','packet','segment'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> When received at the physical layer of a host, the bits are formatted into a frame at the data link layer. A packet is the PDU at the network layer. A segment is the PDU at the transport layer. A file is a data structure that may be used at the application layer.</p></div>');
	// pool.AddNA('43. Refer to the exhibit. ServerB is attempting to contact HostA. Which two statements correctly identify the addressing that ServerB will generate in the process? (Choose two.)', null, null);
	// pool.AddSA('44. Which method allows a computer to react accordingly when it requests data from a server and the server takes too long to respond?', null, 'response timeout', ['encapsulation','flow control','access method'], 1, '<div class="message_box success"><p><b>Explanation:</b> If a computer makes a request and does not hear a response within an acceptable amount of time, the computer assumes that no answer is coming and reacts accordingly.</p></div>');

	// pool.AddMA('46. Which two OSI model layers have the same functionality as a single layer of the TCP/IP model? (Choose two.)', null, ['data link','physical'], ['network','session','transport'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> The OSI data link and physical layers together are equivalent to the TCP/IP network access layer. The OSI transport layer is functionally equivalent to the TCP/IP transport layer, and the OSI network layer is equivalent to the TCP/IP internet layer. The OSI application, presentation, and session layers are functionally equivalent to the application layer within the TCP/IP model.</p></div>');
	// pool.AddSA('47. At which layer of the OSI model would a logical address be added during encapsulation?', null, 'network layer', ['physical layer','data link layer','transport layer'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Logical addresses, also known as IP addresses, are added at the network layer. Physical addresses are edded at the data link layer. Port addresses are added at the transport layer. No addresses are added at the physical layer.</p></div>');
	// pool.AddSA('48. What is a characteristic of multicast messages?', null, 'They are sent to a select group of hosts.', ['They are sent to all hosts on a network.','They must be acknowledged.','They are sent to a single destination.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Multicast is a one-to-many type of communication. Multicast messages are addressed to a specific multicast group.</p></div>');
	// pool.AddSA('49. Which statement is correct about network protocols?', null, 'They define how messages are exchanged between the source and the destination.', ['Network protocols define the type of hardware that is used and how it is mounted in racks.','They all function in the network access layer of TCP/IP.','They are only required for exchange of messages between devices on remote networks.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> Network protocols are implemented in hardware, or software, or both. They interact with each other within different layers of a protocol stack. Protocols have nothing to do with the installation of the network equipment. Network protocols are required to exchange information between source and destination devices in both local and remote networks.</p></div>');
	// pool.AddSA('50. What is an advantage of network devices using open standard protocols?', null, 'A client host and a server running different operating systems can successfully exchange data.', ['Network communications is confined to data transfers between devices from the same vendor.','Internet access can be controlled by a single ISP in each market.','Competition and innovation are limited to specific types of products.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> An advantage of network devices implementing open standard protocols, such as from the TCP/IP suite, is that clients and servers running different operating systems can communicate with each other. Open standard protocols facilitate innovation and competition between vendors and across markets, and can reduce the occurrence of monopolies in networking markets.</p></div>');

	// pool.AddSA('53. Why would a Layer 2 switch need an IP address?', null, 'to enable the switch to be managed remotely', ['to enable the switch to send broadcast frames to attached PCs','to enable the switch to function as a default gateway','to enable the switch to receive frames from attached PCs'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> A switch, as a Layer 2 device, does not need an IP address to transmit frames to attached devices. However, when a switch is accessed remotely through the network, it must have a Layer 3 address. The IP address must be applied to a virtual interface rather than to a physical interface. Routers, not switches, function as default gateways.</p></div>');
	// pool.AddSA('54. Refer to the exhibit. An administrator is trying to configure the switch but receives the error message that is displayed in the exhibit. What is the problem?', '<img src="https://a5m9a8c3.rocketcdn.me/wp-content/uploads/2019/12/i208399v1n1_Question201.png">', 'The administrator must first enter privileged EXEC mode before issuing the command.', ['The entire command, configure terminal, must be used.','The administrator is already in global configuration mode.','The administrator must connect via the console port to access global configuration mode.'], 1, '<div class="message_box success"><p><strong>Explanation:</strong> In order to enter global configuration mode, the command configure terminal, or a shortened version such as config t, must be entered from privileged EXEC mode. In this scenario the administrator is in user EXEC mode, as indicated by the &gt; symbol after the hostname. The administrator would need to use the enable command to move into privileged EXEC mode before entering the configure terminal command.</p></div>');
	// pool.AddSA('55. What term describes a network owned by one organization that provides safe and secure access to individuals who work for a different organization?', null, 'extranet', ['cloud','BYOD','quality of service'], 1, null);
	// pool.AddSA('56. What term describes storing personal files on servers over the internet to provide access anywhere, anytime, and on any device?', null, 'cloud', ['BYOD','quality of service','converged network'], 1, null);
	// pool.AddSA('57. What term describes a network where one computer can be both client and server?', null, 'peer-to-peer', ['cloud','BYOD','quality of service'], 1, null);
	// pool.AddSA('58. What term describes a type of network used by people who work from home or from a small remote office?', null, 'SOHO network', ['BYOD','quality of service','converged network'], 1, null);
	// pool.AddSA('59. What term describes a computing model where server software runs on dedicated computers?', null, 'client/server', ['internet','intranet','extranet'], 1, null);
	// pool.AddSA('61. What term describes a technology that allows devices to connect to the LAN using an electrical outlet?', null, 'powerline networking', ['internet','intranet','extranet'], 1, null);
	// pool.AddSA('62. What term describes a policy that allows network devices to manage the flow of data to give priority to voice and video?', null, 'quality of service', ['internet','intranet','extranet'], 1, null);
	// pool.AddSA('63. What term describes a private collection of LANs and WANs that belongs to an organization?', null, 'intranet', ['internet','extranet','peer-to-peer'], 1, null);
	// pool.AddSA('64. What term describes the ability to use personal devices across a business or campus network?', null, 'BYOD', ['internet','intranet','extranet'], 1, null);
	// pool.AddSA('65. At which OSI layer is a source IP address added to a PDU during the encapsulation process?', null, 'network layer', ['data link layer','transport layer','application layer'], 1, null);
	// pool.AddSA('66. At which OSI layer is a destination port number added to a PDU during the encapsulation process?', null, 'transport layer', ['data link layer','network layer','application layer'], 1, null);
	// pool.AddSA('67. At which OSI layer is data added to a PDU during the encapsulation process?', null, 'application layer', ['data link layer','network layer','transport layer'], 1, null);
	// pool.AddSA('68. At which OSI layer is a source IP address added to a PDU during the encapsulation process?', null, 'network layer', ['data link layer','application layer','presentation layer'], 1, null);
	// pool.AddSA('69. Which of the following is the name for all computers connected to a network that participate directly in network communication?', null, 'Host', ['Servers','Intermediary device','media'], 1, '<div class="message_box success"><p><b>Explanation:</b> Hosts are all computers connected to a network that participate directly in network communication.</p></div>');
	// pool.AddSA('70. At which OSI layer is a destination IP address added to a PDU during the encapsulation process?', null, 'network layer', ['application layer','transport layer','presentation layer'], 1, null);
	// pool.AddSA('71. At which OSI layer is a source MAC address added to a PDU during the encapsulation process?', null, 'data link layer', ['application layer','transport layer','presentation layer'], 1, null);
	// pool.AddSA('72. At which OSI layer is a source port number added to a PDU during the encapsulation process?', null, 'transport layer', ['application layer','network layer','presentation layer','data link layer'], 1, null);
	// pool.AddSA('73. At which OSI layer is a destination MAC address added to a PDU during the encapsulation process?', null, 'data link layer', ['transport layer','application layer','network layer'], 1, null);
	// pool.AddSA('74. When data is encoded as pulses of light, which media is being used to transmit the data?', null, 'Fire optic cable', ['Wireless','Copper cable'], 1, '<div class="message_box success"><p><b>Explanation:</b> Fiber-optic cable is the media is being used to transmit the data when data is encoded as pulses of light.</p></div>');

	console.log(pool.GetJSON());

}

function BuildQuestions() {
	// Generate them and put them in HTML
	quizSpace.innerHTML = pool.Generate(20, false);
}

function CheckQuestions() {
	// Check the answers
	let res : Array<any> = pool.CheckAnswers(Quiz.GetScoringFunction(Quiz.InbuiltScoringFunction.AllOrNothing));
	const percent : number = Math.floor(100 * res[0] / res[1]);
	scoreSpace.innerText = "Scored: " + res[0] + " out of " + res[1] + " (" + percent + "%)";
}





export function Init() {
	PopulateGlobalHTMLElements();
	
	Questions.CreateQuestions(pool);

	CreateQuestions();
	BuildQuestions();

	// let pool:Quiz.QuestionBank = new Quiz.QuestionBank();
}

Init();

// Test();


// quizlet.innerHTML = "foo";